### ISSUE TITLE
RFMix make

### ISSUE THREAD

**Issue by ftlin22** [slowkoni/rfmix#3]
Hi, 
Thank you for creating this, unfortunately I am unable to compile the makefile. Is there something I need to perform to execute this correctly?

**Comment by gtsambos** [comment]
I am having the same problem. When I run ```automake``` in the main directory, I get the following errors:

```
6200D-132482-M:rfmix gtsambos$ automake
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:9: error: required file 'config.h.in' not found
Makefile.am: error: required file './depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
```

**Comment by slowkoni** [comment]
autoreconf —force —install
./configure
make
(optional: [sudo] make install

Otherwise run from the source directory or manually copy the executables to places they are found by your PATH setting)

Let me know if that doesn’t work, maybe I need to update something for a new version of automake or autoconf or something.


--
Mark Koni Wright, Ph. D.
NOTE: This account used to trap spam from sites that require an email login.

Use slowkoni at icloud dot com as my personal account.

Use markoni.wright at gmail dot com for non-Stanford professional or consulting business email

Use mhwright at stanford dot edu for Stanford or Cornell email. mhw6 at cornell dot edu will work for life but Stanford spam filters it.

**Comment by gtsambos** [comment]
Great, thanks for commenting so promptly! It works for me now.

**Comment by hguturu** [comment]
This worked for me:

aclocal
autoheader
autoconf
automake --add-missing
./configure
make

**Comment by slowkoni** [comment]
That is the long way to do it, but yes the autoconf/automake process needs to be run before the ./configure script will exist. Since the ./configure script is generated and should never be hand edited, it is not in the GitHub sources and so the steps that generate it must be run. Automake requires some additional files that it usually copies into the source tree, the —add-missing flag is the correct flag to add. In its error message it actually was saying to do that. I just find it easier to do “autoreconf —force —install” as that usually takes care of everything in one step. Good thing to remember for other source trees which like me do not include the configure script or the various shell scripts automake copies into the tree, but I’ve seen autoreconf fail before and then I had to resort to what you did below. I should add something to the README.md for this. Thought I had but perhaps not.

K

**Comment by hguturu** [comment]
Oh I think I realized why "autoreconf --force --install" didn't work for me. 
The autoformatting of the dashes causes copy pasting that command to yield an error-
autoreconf: 'configure.ac' or 'configure.in' is required"

Glad to know the shortcut.
